repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: commitmsg
        name: Validation messages commits
        entry: python scripts/validate_commit_msg.py
        language: system
        stages: [commit-msg]
        args: [$1]