sonar.projectKey=MichaBerna_dashboard-neobanque
sonar.projectName=Dashboard NeoBanque
sonar.organization=michaberna
sonar.sources=api,dashboard
sonar.exclusions=**/tests/**,**/__pycache__/,"**/__init__.py"
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13