name: SonarCloud

on: [push, pull_request]

jobs:
  sonarcloud:
    name: Analyse Sonarcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r api/requirements.txt
          pip install -r dashboard/requirements.txt
          pip install -r modele/entrainement/requirements.txt

      - name: Run tests with coverage
        run: pytest --cov=dashboard/ --cov=api/ --cov-report=xml:coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io